### ISSUE TITLE
How to handle invalid values

### ISSUE THREAD

**Issue by lmullany** [lmullany/flusight1_hub#11]
There are numerous submissions that would not pass basic validation checks if such checks were in place at the time of submission. 

For example, we have model submissions where the cdf max exceeds 1, or the pmf does not sum to 1. Checking these requires some tolerance for precision differences, (i.e. 1 ~= 1.000001), but there examples where the difference between the expected max or sum is substantially different than 1

A summary of how many submissions fail these checks would be helpful

**Comment by nickreich** [comment]
@annakrystalli do you know how the current validations would handle a situation where there is some small precision differences?

**Comment by lmullany** [comment]
![image](https://github.com/lmullany/flusight1_hub/assets/12236192/89722b21-08ac-47ec-bc65-9966f640ce85)

**Comment by annakrystalli** [comment]
Validations use `dplyr::near()` to determine equality and the tolerance is machine specific, determined by `tol = .Machine$double.eps^0.5)`

**Comment by lmullany** [comment]
okay, so when we use near(), depends on machine, but likely to be somewhere around ~10% of pmfs

**Comment by elray1** [comment]
At minimum, it seems like we should document specific validation failures that would impact analyses that people want to do and suggest mitigations?  For example, if probabilities don’t sum to 1, people using the data run the risk of doing invalid analyses.  We’ll want to either correct that or document it so people using the data know they need to correct that.

**Comment by elray1** [comment]
Here's the guidance that was provided for the 2015/2016 challenge: "The probabilities for each prediction for each milestone should be positive and sum to 1. If the sum is greater than 0.9 or less than 1.1, the probabilities will be normalized to 1.0. If any probability is negative or the sum is outside of that range, the forecast will be discarded."

So maybe we could replicate that process in our cleanup here?
