### ISSUE TITLE
team and model names across season

### ISSUE THREAD

**Issue by lmullany** [lmullany/flusight1_hub#12]
Some teams changed their name from year to year, and thus a single team-model can have multiple folders in the `model-output` folder. If this change in team-model differs only trivially (for example, spelling name change, or writing our the model name instead of acronym), rather than a substantive change in the model itself, then perhaps we should work towards consolidating these multiple folders

**Comment by bsweger** [comment]
My .02 (and I raised an issue over in the [hubverse-transform](https://github.com/Infectious-Disease-Modeling-Hubs/hubverse-transform/issues/9) repo): any cloud-based data transforms should handle all incoming file/folder names gracefully.

To date, that transform module has assumed that incoming data has gone through the hubverse model-output validation function, but if we want to use it with converted archived data, it should handle these types of edge cases.
