### ISSUE TITLE
No model metadata

### ISSUE THREAD

**Issue by lmullany** [lmullany/flusight1_hub#13]
I believe there are no model metadata files (perhaps I need to do a more thorough search of the original repo and documentation). As a result the `model-metadata` folder is empty. This means that any external functionality that depends on information in this folder would not work, or would need to be adapted to account for situations where model-metadata is missing

**Comment by lmullany** [comment]
Among numerous implications is that we directly know if a team/model is an ensemble of other models, or is a secondary rather than primary model, etc.

**Comment by nickreich** [comment]
In correspondence with CDC, it looks like there might exist some doc/pdf files that have narrative descriptions of the model. Seems like it might be good to try to capture some basic metadata fields for each model, even if it means some painstaking manual entry. Here's a start at a possible list, following the [recommended standards](https://hubdocs.readthedocs.io/en/latest/user-guide/model-metadata.html#recommended-standards), where * indicates required:
 - team_name*
 - model_id* (thinking that we could use one field here, and standardize when possible as mentioned in #12 )
 - model_contributors* 
 - methods*
 - ensemble_of_hub_models*
 - website_url 
 - citation
 - ensemble_of_models

**Comment by nickreich** [comment]
Model Metadata now available here: https://github.com/cdcepi/FluSight-forecasts/tree/d6176ddf0426ba66662f2fd5e056a8fde76362d8/Team%20Methodologies

**Comment by lmullany** [comment]
okay, that's helpful - at first glance, this does look painstaking, but could be an important process to go through.. Not sure that it looks very complete though. I'll take a closer look.

**Comment by lmullany** [comment]
Melissa Kerr and Martha Horn have been working on creating yaml files for each of the team-models. A push of these yaml files to the model-metadata folder will be part of the solution to this issue

**Comment by lmullany** [comment]
Closed via !33
