### ISSUE TITLE
how to define origin_date from epi year and week

### ISSUE THREAD

**Issue by lmullany** [lmullany/flusight1_hub#19]
Based on #10 ,  we are going to derive an `origin_date` based on EWXX. From the original instructions

![image](https://github.com/lmullany/flusight1_hub/assets/12236192/383c4a06-b5cb-4a7f-b6e1-bcbc129bf424)

we, see that EWXX represents the **latest MMWR week of data** used in the forecast..  Some options for deriving origin_date:
1. Set to the date of the first day of the epiweek represented by EWXX
2. Set to the date of the last day of the epiweek represented by EWXX (i.e option 1 plus 6 days)
3. Set to the date of the first day of the week following EWXX (ie. EWXX + 1) (i.e. option 1 plus 7 days)

**Comment by nickreich** [comment]
The [convention at the US COVID-19 Forecast Hub](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#target_end_date) is to use the final Saturday of an epiweek as the target_end_date, so I think that would suggest option 2 might be the most consistent with prior behavior.

**Comment by lmullany** [comment]
Closing via #22
